name: SuperCommands
version: '1.1.0'
main: me.martin.superCommands.SuperCommands
api-version: '1.21'
authors: [Martin]
description: A Minecraft Paper plugin that adds new commands.
website: https://github.com/martin-coding/mcplugin-WelcomeMessages
